scrape_configs:
  - job_name: beatless-rawcli
    scrape_interval: 30s
    static_configs:
      - targets:
          - localhost:9100
    metric_relabel_configs:
      - source_labels:
          - __name__
        regex: rawcli_.*
        action: keep
